name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run tests
        run: just test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Get version from tag or input
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build cross-platform binaries
        run: just build-cross-platform

      - name: Package releases
        run: just package

      - name: Generate checksums
        run: |
          cd dist
          sha256sum *.tar.gz *.zip > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt
          body: |
            ## Installation

            ### Go Install
            ```bash
            go install github.com/singletoned/taidy@${{ steps.version.outputs.version }}
            ```

            ### Download Binary
            Download the appropriate binary for your platform from the assets below.

            ### Homebrew
            ```bash
            brew install singletoned/tap/taidy
            ```

            ## Changes

            See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          tap: singletoned/homebrew-tap
          formula: taidy
          tag: ${{ github.ref_name }}
          revision: ${{ github.sha }}
